### ISSUE TITLE
总算成功了

### ISSUE THREAD

**Issue by kevzcr** [yabostone/picgo-plugin-rclone#5]
![image](https://user-images.githubusercontent.com/88956040/198208259-a7e213a3-5d02-4f08-9901-d1528dc7c737.png)
有几点疑问：
1.文件有大小限制吗？
2.上传后都会套一个文件夹，文件夹名即所上传的文件名，但真正的文件名却被改了，有办法不要这个文件夹，也不要改文件的名字吗？

**Comment by yabostone** [comment]
1.文件大小是直接调用rclone进行的，如果环境在国内，那么好像是没有大小限制，只是会报错。
2.好像是你设置上传路径的时候设置了文件夹名作为文件夹，修改上传路径的内容就可以。好像直接上传路径不添加文件夹就可以了。

**Comment by yabostone** [comment]
请尝试修改不同的上传路径进行路径匹配，更多的细节可以看picgo的s3插件下的路径上传机制。

**Comment by zbb7001** [comment]
> 1.文件大小是直接调用rclone进行的，如果环境在国内，那么好像是没有大小限制，只是会报错。 2.好像是你设置上传路径的时候设置了文件夹名作为文件夹，修改上传路径的内容就可以。好像直接上传路径不添加文件夹就可以了。
##  我试了3种路径  可以看到没有一种为原始文件名。
![image](https://user-images.githubusercontent.com/101622397/218306042-6232646f-dd0c-4a99-bbb6-f8d6aaf151dd.png)
![image](https://user-images.githubusercontent.com/101622397/218306269-4b393fcd-9e0d-4801-950e-55c67aa8bb40.png)
## 造成的影响就是复制到剪贴板中的图片网址没用， 麻烦大佬再帮帮忙。
另外还有2个问题
1.能否上传文档等其他文件？
2.如果我想用autohotkey来调用rclone插件的话，我该如何设置呢？  

感谢提供的这么好的软件，方便了很多。

**Comment by 3verness** [comment]
请问套文件夹的问题有解决么？我也遇到了相同的问题。

**Comment by yabostone** [comment]
这个是所有的云存储都是这样的么？还是只是onedrive的部分？

**Comment by zbb7001** [comment]
> 请问套文件夹的问题有解决么？我也遇到了相同的问题。

      "remoteBucketName": "",           ;;;此处留空
 "remoteBucketName": "/",               ;;;如使用PicGo-1.3.1上传，此处填写/
"uploadPath": "jt",　　　　　　　;;; 此处填写你上传到onedrive的文件夹名
